/**
 * This file is generated by plopfile
 * avoid modifications and DO NOT remove the comments
 * comments above is used by plopfile to localize the line which  is going to generate the code
 */
// append_type_import
import { InitialState as User } from 'core/store/user'

export type Store = {
  // append_type_key
  user: User
}
